---
- name: Pre-requisites check on all nodes
  hosts: all
  become: yes

  vars:
  - k0s_version: v1.23.6+k0s.0
  - k0s_use_custom_config: true

  roles:
  - role: pre.ops/
    tags: pre-ops
  - role: extra.ops/cni-plugins.ops/
    tags: extra-ops

- name: Write/generate k0s config file on control plane node
  hosts:
  - initial_controller
  - controller
  gather_facts: yes
  become: yes

  vars:
  - loadbalancer_host: 10.140.40.119
  - k0s_use_custom_config: true

  roles:
  - role: k0s.ops/configure.ops/

- name: Configure initial k0s control plane node
  hosts: initial_controller
  gather_facts: yes
  become: yes

  roles:
  - role: k0s.ops/init.ops/
    tags:
    - k0s-ops
    - init-ops

- name: Configure k0s control plane (master) nodes
  hosts: controller
  gather_facts: yes
  become: yes
  serial: 1

  roles:
  - role: k0s.ops/controller.ops/
    tags:
    - k0s-ops
    - controller-ops

- name: Configure k0s worker nodes
  hosts: worker
  become: yes

  roles:
  - role: k0s.ops/worker.ops/
    tags:
    - k0s-ops
    - worker-ops

- name: Export k0s kubeconfig
  hosts: initial_controller

  vars:
  - context_name: staging

  roles:
  - role: post.ops/
