---
- name: Download k0s on all nodes
  hosts: all
  become: yes

  vars:
    k0s_version: v1.23.5+k0s.1

  roles:
    - role: pre.ops/
      tags: pre-ops

- name: Configure initial k0s control plane node
  hosts: initial_controller
  gather_facts: yes
  become: yes

  roles:
    - role: k0s.ops/initial_controller.ops
      tags: init-ops

- name: Configure k0s control plane (master) nodes
  hosts: controller
  gather_facts: yes
  become: yes
  serial: 1

  roles:
    - role: k0s.ops/controller.ops
      tags: controller-ops

- name: Configure k0s worker nodes
  hosts: worker
  become: yes

  roles:
    - role: k0s.ops/worker.ops
      tags: worker-ops
