---
- name: Copy kubeconfig
  fetch:
    src: "{{ kube_dir }}/config"
    dest: "{{ artifacts_dir }}/{{ context_name }}-k0s-config"
    flat: yes
    validate_checksum: no

- name: "print kubeconfig command"
  debug:
    msg: "To use Cluster: export KUBECONFIG={{ artifacts_dir }}/{{ context_name }}-k0s-config"
