---
multi-node:
  children:
    initial_controller:
      hosts:
        staging-k8s-master-1:
    worker:
      hosts:
        staging-k8s-worker-1:
        staging-k8s-worker-2:
        staging-k8s-worker-3:

  hosts:
    staging-k8s-master-1:
      ansible_host: 10.119.23.151
    staging-k8s-worker-1:
      ansible_host: 10.119.23.161
    staging-k8s-worker-2:
      ansible_host: 10.119.23.162
    staging-k8s-worker-3:
      ansible_host: 10.119.23.163

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_yubikey.pub
