---
- name: "Write the k0s token file on controller"
  template:
    src: controller-token.j2
    dest: "{{ k0s_config_dir }}/controller-token"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: Check if controller service already exists
  stat:
    path: /etc/systemd/system/k0scontroller.service
  register: is_k0scontroller_service_exist

- name: Create k0s controller service with install command
  register: install_controller_cmd
  shell: "k0s install controller --config {{ k0s_config_dir }}/k0s.yaml --token-file {{ k0s_config_dir }}/controller-token {{ extra_args | default(omit) }}"
  changed_when: install_controller_cmd | length > 0
  when: not is_k0scontroller_service_exist.stat.exists

- name: Setup custom environment variables for systemd unit
  include_role:
    name: set-env.ops/

- name: "Enable and check k0s service"
  become: true
  systemd:
    name: k0scontroller
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: "Wait for k8s apiserver"
  wait_for:
    host: localhost
    port: 6443
    timeout: 180
