---
- name: Verify k0s installation
  become: true
  block:
    - name: Check if k0s is installed
      shell: "command -v k0s"
      register: is_k0s_installed
      changed_when: false
      failed_when: is_k0s_installed.rc != 0

  rescue:
  - name: Install k0s using script
    shell: "curl -fsSL https://get.k0s.sh | sudo K0S_VERSION={{ k0s_version }} sh"
