---
name: Install CNI solution
block:
  - include_tasks: "{{ playbook_dir }}/roles/extra.ops/cilium.ops/tasks/install.yml"

  - name: Check if Cilium CLI is present on the node
    command: "command -v cilium"
    register: is_present

  - name: Install Cilum with Cilium CLI
    ansible.builtin.command: "cilium install"
    when: is_present
when: cni == "cilium"
